Header header

int32 body_id
int32 tracking_status
int32 gesture

geometry_msgs/Point position2D # x,y in camera frame

geometry_msgs/Point centerOfMass

#Pose of interesting joints
geometry_msgs/Pose head_pose
geometry_msgs/Pose neck_pose
geometry_msgs/Pose shoulder_pose
geometry_msgs/Pose spine_mid_pose
geometry_msgs/Pose spine_bottom_pose

geometry_msgs/Pose left_shoulder_pose
geometry_msgs/Pose left_elbow_pose
geometry_msgs/Pose left_wrist_pose
geometry_msgs/Pose left_hand_pose

geometry_msgs/Pose right_shoulder_pose
geometry_msgs/Pose right_elbow_pose
geometry_msgs/Pose right_wrist_pose
geometry_msgs/Pose right_hand_pose

geometry_msgs/Pose left_hip_pose
geometry_msgs/Pose left_knee_pose
geometry_msgs/Pose left_foot_pose

geometry_msgs/Pose right_hip_pose
geometry_msgs/Pose right_knee_pose
geometry_msgs/Pose right_foot_pose



